---
parser: babel-eslint
extends:
  - eslint:recommended
  - airbnb
env:
  browser: true
  jest: true
globals:
  Class: false
parserOptions:
  ecmaVersion: 2018
  sourceType: module
  ecmaFeatures:
    jsx: true
plugins:
  - react
  - react-native
  - flowtype
  - jsx-a11y
  - import
rules:
  array-bracket-spacing:
    - 2
    - always
    - singleValue: false
      objectsInArrays: false
      arraysInArrays: false
  function-paren-newline:
    - 0
  max-len:
    - 2
    - 120
    - 2
    - ignoreStrings: true
      ignoreComments: true
      ignoreUrls: true
      ignoreTemplateLiterals: true
      ignoreRegExpLiterals: true
  no-underscore-dangle:
    - error
    - enforceInMethodNames: true
  react/jsx-filename-extension:
    - 2
    - extensions:
      - .js
  react/jsx-one-expression-per-line: 0
  react/prop-types: 0
  react/sort-comp:
    - 2
    - order:
      - 'type-annotations'
      - 'static-methods'
      - 'lifecycle'
      - 'everything-else'
      - 'render'
  react-native/no-inline-styles:
    - error
